import express from 'express';
import cors from 'cors';
import dotenv from 'dotenv';
import recipesRouter from './routes/recipes.js';
import { query } from './db.js';
dotenv.config();
const app = express(); app.use(cors()); app.use(express.json());
app.get('/api/health', async (_req, res) => { try { await query('SELECT 1'); res.json({ status: 'ok' }); } catch (e) { res.status(500).json({ status: 'db_error' }); } });
app.use('/api/recipes', recipesRouter);
const PORT = process.env.PORT || 4000; app.listen(PORT, () => console.log(`API running on http://localhost:${PORT}`));
