version: '3.9'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: recipes_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
  mongo:
    image: mongo:6
    ports:
      - '27017:27017'
    volumes:
      - mongodata:/data/db
volumes:
  pgdata:
  mongodata:
